CREATE DATABASE GRUPO_6_DB;
USE GRUPO_6_DB;
CREATE TABLE AVION
(
	ID_AVION INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	CAPACIDAD INT NOT NULL
);
CREATE TABLE CLIENTE
(
	ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DIRECCION VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(30) NOT NULL,
	DNI INT NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	APELLIDO VARCHAR(40) NOT NULL,
	FEC_NACIMIENTO DATE NOT NULL
	
);
CREATE TABLE VUELO
(
	ID_VUELO INT NOT NULL PRIMARY KEY,
	ID_AVION INT NULL REFERENCES AVION(ID_AVION),
	DESDE VARCHAR(30) NOT NULL,
	HACIA VARCHAR(30) NOT NULL,
	HORARIO_PARTIDA DATE,
	HORARIO_LLEGADA DATE
);
CREATE TABLE PAQUETE
(
	ID_PAQUETE INT NOT NULL PRIMARY KEY,
	PRECIO NUMERIC(8,2) NOT NULL,
	CANT_PERSONAS INT NOT NULL,
	ID_VUELO INT NOT NULL REFERENCES VUELO(ID_VUELO)
);
CREATE TABLE PAQUETE_CLIENTE
(
	ID_CLIENTE INT NOT NULL REFERENCES CLIENTE(ID_CLIENTE),
	ID_PAQUETE INT NOT NULL  REFERENCES PAQUETE(ID_PAQUETE),
	PRIMARY KEY(ID_CLIENTE,ID_PAQUETE)
);
CREATE TABLE RESERVA
(
	ID_RESERVA INT NOT NULL PRIMARY KEY,
	NRO_TARJETA INT NOT NULL,
	COD_VERIFICADOR INT NOT NULL,
	FECHA_VENCIMIENTO INT NOT NULL,
	TOTAL NUMERIC(8,2) NOT NULL
);
CREATE TABLE RESERVA_PAQUETE
(
	ID_RESERVA INT NOT NULL REFERENCES RESERVA(ID_RESERVA),
	ID_PAQUETE INT NOT NULL REFERENCES PAQUETE(ID_PAQUETE)
);
INSERT INTO AVION VALUES(1,'TANGO01',50);
INSERT INTO AVION VALUES(2,'TANGO02',50);
INSERT INTO AVION VALUES(3,'TANGO03',50);

INSERT INTO CLIENTE (`ID_CLIENTE`, `DIRECCION`, `EMAIL`, `TELEFONO`, `DNI`, `NOMBRE`, `APELLIDO`, `FEC_NACIMIENTO`) VALUES (NULL, 'Calle falsa 123', 'admin@admin.com.ar', '11111111111', '11111111', 'Guillermo', 'Telijo', '1994-04-11');
INSERT INTO CLIENTE (`ID_CLIENTE`, `DIRECCION`, `EMAIL`, `TELEFONO`, `DNI`, `NOMBRE`, `APELLIDO`, `FEC_NACIMIENTO`) VALUES (NULL, 'Av Siempre Viva', 'root@admin.com.ar', '2222222222', '22222222', 'Esteban', 'Quito', '1994-10-18');